name: lint-n-test

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  lint-n-test:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go mod tidy
          go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest

      - name: Test
        run: go test -v ./...
      #        run: go test -v ./... -args -ginkgo.randomizeAllSpecs -ginkgo.trace


# remove gitleaks has we need to pay now
#      - name: gitleaks
#        uses: zricethezav/gitleaks-action@master
#        with:
#          config-path: .gitleaks.toml
