name: lint-n-test

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  lint-n-test:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod tidy
          go mod download
      #          go install github.com/onsi/ginkgo/ginkgo

      - name: Test
        run: go test -v ./...
      #        run: go test -v ./... -args -ginkgo.randomizeAllSpecs -ginkgo.trace

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.32

      - name: gitleaks
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: .gitleaks.toml
